### ISSUE TITLE
Custom Server Versions aren't correctly recognized

### ISSUE THREAD

**Issue by JokerGermany** [maubot/rsvc#2]
[!servers match synapse < 1.56.0](https://matrix.to/#/!mZyxRMVqVYjdiEIQMo:matrix.org/$w3MXTnjbfIJ82T1T4nOIwRe5F3pQHTuQOLxy3zW9c5c?via=matrix.org&via=chat.virtuos.uni-osnabrueck.de&via=tu-dresden.de)
> - aria-net.org (Synapse 1.63.1.arianet.1) with @﻿_﻿b﻿i﻿f﻿r﻿o﻿s﻿t﻿_﻿b﻿o﻿t﻿:﻿a﻿r﻿i﻿a﻿-﻿n﻿e﻿t﻿.﻿o﻿r﻿g and @﻿_﻿b﻿i﻿f﻿r﻿o﻿s﻿t﻿_﻿g﻿u﻿c﻿k﻿y﻿y﻿_﻿=﻿4﻿0﻿l﻿i﻿b﻿r﻿e﻿-﻿c﻿h﻿a﻿t﻿.﻿n﻿e﻿t﻿:﻿a﻿r﻿i﻿a﻿-﻿n﻿e﻿t﻿.﻿o﻿r﻿g

**Comment by tulir** [comment]
That's not a valid [PEP 440](https://peps.python.org/pep-0440/) version string
